version: '3'
services:
  backend:
    build: backend
    volumes:
      - './backend/:/app/'
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  db:
    image: postgres
    env_file:
      - backend/.env
    ports:
      - "5433:5432"
    volumes:
      - '/var/lib/postgresql/data'
