version: '3'
services:
  backend:
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - backend/.env
    volumes:
      - './backend/:/app/'
      - '~/media/avatars/:/app/api/avatars'
  frontend:
    build: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - '~/media/avatars/:/usr/share/nginx/html/media/avatars'
  postgres:
    image: postgres
    env_file:
      - backend/.env
    ports:
      - "5433:5432"
    volumes:
      - 'data-postgres:/var/lib/postgresql/data'


volumes:
  data-postgres:
    driver: local