version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - '.:/code'
    working_dir: /code
    entrypoint: /code/docker-entrypoint.sh
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - '/var/lib/postgresql/data'
