version: '3'
services:
  backend:
    image: registry.gitlab.com/marshalx/innowisegrouptesttask/backend:${CI_COMMIT_SHA}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
  frontend:
    image: registry.gitlab.com/marshalx/innowisegrouptesttask/frontend:${CI_COMMIT_SHA}
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - .env
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - '/var/lib/postgresql/data'
