version: '3'
services:
  backend:
    image: registry.gitlab.com/marshalx/innowisegrouptesttask/backend:${CI_COMMIT_SHA}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - '~/media/avatars/:/app/api/avatars'
  frontend:
    image: registry.gitlab.com/marshalx/innowisegrouptesttask/frontend:${CI_COMMIT_SHA}
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - '~/media/avatars/:/usr/share/nginx/html/media/avatars'
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - 'data-postgres:/var/lib/postgresql/data'


volumes:
  data-postgres:
    driver: local
