version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: /app/docker-entrypoint.sh
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - '/var/lib/postgresql/data'
